[dependencies]
"wasmer/winterjs" = "^0.4.4"

[fs]
"/web" = ".vercel/output/static"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
